#pragma once

enum SortType
{
    BATTING_AVERAGE = 1, BATTING_STRIKE_RATE, FOURS_AND_SIXES, STRIKE_RATE_WITH_SIX_AND_FOUR, BATTING_AVERAGE_WITH_STRIKE_RATE,
    RUNS_WITH_BATTING_AVERAGE, BOWLING_AVERAGE, BOWLING_STRIKE_RATE, ECONOMY_RATE, STRIKE_RATE_WITH_FOUR_AND_FIVE_WICKETS,
    BOWLING_AVERAGE_WITH_STRIKE_RATE, WICKETS_WITH_BOWLING_AVERAGE, BATTING_AND_BOWLING_AVERAGE, MOST_RUNS_AND_WICKETS,
    HUNDRED_AND_AVERAGE
};