#pragma once

enum SortType
{
    BATTING_AVERAGE = 1, BATTING_STRIKE_RATE, FOURS_AND_SIXES, STRIKE_RATE_WITH_SIX_AND_FOUR, BATTING_AVERAGE_WITH_STRIKE_RATE,
    RUNS_WITH_BATTING_AVERAGE, BOWLING_AVERAGE, BOWLING_STRIKE_RATE, ECONOMY_RATE
};